while True:
  print('Bienvenido a la Tiendita de la esquina')
  nombre=input('nombre del vendedor: ')
  articulo1=input('articulo 1: ')
  precio1=int(input('precio: '))
  articulo2=input('articulo 2: ')
  precio2=int(input('precio: '))
  articulo3=input('articulo 3: ')
  precio3=int(input('precio: '))
  articulo4=input('articulo 4: ')
  precio4=int(input('precio: '))
  articulo5=input('articulo 5: ')
  precio5=int(input('precio: '))
  
  print('el subtotal es: ',
  precio1+precio2+precio3+precio4+precio5)
  print('IVA: 16%')
  print('total:', (precio1+precio2+precio3+precio4+precio5)*1.16)
  print('--------------------------------')
  print('TICKET')
  print('lo atendio', nombre)
  print('articulo 1:', articulo1)
  print('precio: ', precio1)
  print('articulo 2:', articulo2)
  print('precio: ', precio2)
  print('articulo 3:', articulo3)
  print('precio: ', precio3)
  print('articulo 4:', articulo4)
  print('precio: ', precio4)
  print('articulo 5:', articulo5)
  print('precio: ', precio5)
  print('el subtotal es: ',precio1+precio2+precio3+precio4+precio5)
  print('IVA: 16%')
  print('total:', (precio1+precio2+precio3+precio4+precio5)*1.16)
  print('Gracias por comprar, vuelva pronto')